/* ======================== 工程部模块 ====================  */
/*==============================================================*/
/* 工程施工计划表   */
/*==============================================================*/
DROP TABLE IF EXISTS IB_WORKS_PLAN;
CREATE TABLE IB_WORKS_PLAN (PROJECTNO VARCHAR(64), PROJECTNAME VARCHAR(64), PROJECTTYPE VARCHAR(16), CUSTOMERNAME VARCHAR(64), PRODUCTMANAGE VARCHAR(64), WORKINGDAY INT(8), STARTTIME DATETIME, ENDTIME DATETIME, BUYSTARTTIME DATETIME, BUYENDTIME DATETIME, PRODSTARTTIME DATETIME, PRODENDTIME DATETIME, PRODOUTSTARTTIME DATETIME, PRODOUTENDTIME DATETIME, ID VARCHAR(64), SCOPEID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;
DROP TABLE IF EXISTS IB_WORKS_PLAN_S;
CREATE TABLE IB_WORKS_PLAN_S (PROJECTNAME VARCHAR(128), PRODUCTIONMODE VARCHAR(64), PRODUCTIONADDRESS VARCHAR(128), WORKINGDAY INT(8), STARTTIME DATETIME, ENDTIME DATETIME, ID VARCHAR(64), PARENTID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;

/*==============================================================*/
/* 仓库信息表   */
/*==============================================================*/
DROP TABLE IF EXISTS IB_WAREHOUSE;
CREATE TABLE IB_WAREHOUSE (WAREHOUSENO VARCHAR(64), WAREHOUSENAME VARCHAR(128), WAREHOUSELOCATION VARCHAR(128), ID VARCHAR(64), SCOPEID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;
/*==============================================================*/
/* 物料分类信息表   */
/*==============================================================*/
DROP TABLE IF EXISTS IB_MATERIALS_TYPE;
CREATE TABLE IB_MATERIALS_TYPE (TYPENO VARCHAR(64), TYPENAME DATETIME, PARENTID VARCHAR(64), ISLEAF DATETIME, ID VARCHAR(64), SCOPEID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;

/*==============================================================*/
/* 物料表   */
/*==============================================================*/
DROP TABLE IF EXISTS IB_MATERIALS;
CREATE TABLE IB_MATERIALS (MATERIALNO VARCHAR(64), MATERIALNAME DATETIME, MATERIALPRICE DOUBLE(12,2), MATERIALTYPENO DATETIME, MATERIALUNIT VARCHAR(8), MODEL VARCHAR(64), ID VARCHAR(64), SCOPEID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;

/*==============================================================*/
/*  原料入库表  */
/*==============================================================*/
DROP TABLE IF EXISTS IB_MATERIAL_IN;
CREATE TABLE IB_MATERIAL_IN (
  ID varchar(64) NOT NULL,
  EXECUTIONID varchar(64) DEFAULT NULL,
  ASSIGNEEUSER varchar(128) DEFAULT NULL,
  DONEFLAG int(11) DEFAULT '0',
  USERNAME varchar(128) DEFAULT NULL,
  TASKTITLE varchar(256) DEFAULT NULL,
  NODENAME varchar(128) DEFAULT NULL,
  CREATEDATEBPM datetime DEFAULT NULL,
  EVENTDATE datetime DEFAULT NULL,
  SUPPLIERSNAME varchar(64) DEFAULT NULL,
  WAREHOUSENO varchar(64) DEFAULT NULL,
  WAREHOUSENAME varchar(64) DEFAULT NULL,
  TOTALNUM int(10) DEFAULT NULL,
  AMOUNT double(12,2) DEFAULT NULL,
  AMOUNTBIG varchar(64) DEFAULT NULL,
  REMARK varchar(512) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=INNODB;
/*==============================================================*/
/*  原料入库信息子表  */
/*==============================================================*/
DROP TABLE IF EXISTS IB_MATERIAL_IN_S;
CREATE TABLE IB_MATERIAL_IN_S (
  ID varchar(64) NOT NULL,
  PARENTID varchar(64) DEFAULT NULL,
  MATERIALNO varchar(64) DEFAULT NULL,
  MATERIALNAME varchar(128) DEFAULT NULL,
  MATERIALMODEL varchar(64) DEFAULT NULL,
  MATERIALUNIT varchar(16) DEFAULT NULL,
  MATERIALNUM int(10) DEFAULT NULL,
  AMOUNT double(12,2) DEFAULT NULL,
  MANUFACTURENAME varchar(64) DEFAULT NULL,
  REMARK varchar(512) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=INNODB;
/*==============================================================*/
/*  原料库存管理表  */
/*==============================================================*/
DROP TABLE IF EXISTS IB_WAREHOUSE_MATERIALS;
CREATE TABLE IB_WAREHOUSE_MATERIALS (MATERIALTYPENO VARCHAR(64), MATERIALNO VARCHAR(64), MATERIALNAME VARCHAR(128), MATERIALMODEL VARCHAR(64), MATERIALPRICE DOUBLE(12,2), MATERIALUNIT VARCHAR(8), MATERIALNUM INT(10), WAREHOUSENO VARCHAR(64), WAREHOUSENAME VARCHAR(128), ID VARCHAR(64), SCOPEID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;

/*==============================================================*/
/*  (领料)原料出库表  */
/*==============================================================*/
DROP TABLE IF EXISTS IB_MATERIAL_OUT;
CREATE TABLE IB_MATERIAL_OUT (
  EXECUTIONID varchar(64) DEFAULT NULL,
  ASSIGNEEUSER varchar(128) DEFAULT NULL,
  DONEFLAG int(11) DEFAULT '0',
  ID varchar(64) NOT NULL,
  USERNAME varchar(128) DEFAULT NULL,
  TASKTITLE varchar(256) DEFAULT NULL,
  NODENAME varchar(128) DEFAULT NULL,
  CREATEDATEBPM datetime DEFAULT NULL,
  EVENTDATE datetime DEFAULT NULL,
  BATCHNO varchar(8) DEFAULT NULL,
  WAREHOUSENO varchar(64) DEFAULT NULL,
  PRODUCTNO varchar(64) DEFAULT NULL,
  PRODUCTNAME varchar(256) DEFAULT NULL,
  MATERIALNUM int(10) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=INNODB;
/*==============================================================*/
/*  原料出库信息子表  */
/*==============================================================*/
DROP TABLE IF EXISTS IB_MATERIAL_OUT_S;
CREATE TABLE IB_MATERIAL_OUT_S (
  ID varchar(64) NOT NULL,
  PARENTID varchar(64) DEFAULT NULL,
  MATERIALNO varchar(64) DEFAULT NULL,
  MATERIALNAME varchar(128) DEFAULT NULL,
  MATERIALMODEL varchar(64) DEFAULT NULL,
  MATERIALUNIT varchar(16) DEFAULT NULL,
  MATERIALNUM int(10) DEFAULT NULL,
  MANUFACTURENAME varchar(64) DEFAULT NULL,
  REMARK varchar(512) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=INNODB;
