/* ======================== 工程部模块 ====================  */
/*==============================================================*/
/* 工程施工计划表   */
/*==============================================================*/
DROP TABLE IF EXISTS IB_WORKS_PLAN;
CREATE TABLE IB_WORKS_PLAN (PROJECTNO VARCHAR(64), PROJECTNAME VARCHAR(64), PROJECTTYPE VARCHAR(16), CUSTOMERNAME VARCHAR(64), PRODUCTMANAGE VARCHAR(64), WORKINGDAY INT(8), STARTTIME DATETIME, ENDTIME DATETIME, BUYSTARTTIME DATETIME, BUYENDTIME DATETIME, PRODSTARTTIME DATETIME, PRODENDTIME DATETIME, PRODOUTSTARTTIME DATETIME, PRODOUTENDTIME DATETIME, ID VARCHAR(64), SCOPEID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;
DROP TABLE IF EXISTS IB_WORKS_PLAN_S;
CREATE TABLE IB_WORKS_PLAN_S (PROJECTNAME VARCHAR(128), PRODUCTIONMODE VARCHAR(64), PRODUCTIONADDRESS VARCHAR(128), WORKINGDAY INT(8), STARTTIME DATETIME, ENDTIME DATETIME, ID VARCHAR(64), PARENTID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;


