/* ======================== 设计部模块 ====================  */
/* ====== 自动报价表 =====  */
DROP TABLE IF EXISTS IB_AUTOQUOTE;
CREATE TABLE IB_AUTOQUOTE (CEILINGAREA DOUBLE(12,2), TILEAREA DOUBLE(12,2), FLOORAREA DOUBLE(12,2), PAINTAREA DOUBLE(12,2), TOTALBUILDAREA DOUBLE(12,2), TOTALUSERAREA DOUBLE(12,2), TOTALAMOUNT DOUBLE(15,2), ID VARCHAR(64), SCOPEID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;


